### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by Dvelpro** [ADN-DevTech/3dsMax-Python-HowTos#33]
Excuse me ， Are these examples still applicable in the 3dsMax 2020 ?  if i want to use what can i do something?  i‘m looking forward to your answer  ty

**Comment by kevinvandecar** [comment]
Yes, many of them should have code that will work in 3ds Max 2020, but may not run as-is due to import syntax, potential API changes, etc.  The pymxs ones should be the important examples. Note that the MaxPlus python module has been deprecated and removed from later 3ds Max releases, so I would not develop anything using that module (but it is still documented in the 2020 release docs). Also be aware that 3ds Max 2020 used the Python 2.x interpreter, and in general that is no longer supported due to security concerns and maintainability by the python organization. We would encourage you to move to later version of 3ds Max when you can. 3ds Max 2021 introduced support for python 3. Hope it helps.

**Comment by hugow** [comment]
Yes all these samples target python 3.

**Comment by Dvelpro** [comment]
Think you
